version: "3.1"

services:
  scheduler:
    #image: ghcr.io/dask/dask:latest
    image: rhadi2005/dask-dask:latest
    hostname: scheduler
    volumes:
      #- ./workspace:/opt/workspace
      - ./workspace:/home/jovyan/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    ports:
      - "8786:8786"
      - "8787:8787"
    #restart: no, always, on-failure, unless-stopped
    restart: unless-stopped
    command: ["dask", "scheduler"]

  worker1:
    #image: ghcr.io/dask/dask:latest
    image: rhadi2005/dask-dask:latest
    volumes:
      #- ./workspace:/opt/workspace  
      - ./workspace:/home/jovyan/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    restart: unless-stopped
    extra_hosts:
      - "ecs-python2:10.50.0.194"
    command: ["dask", "worker", "tcp://ecs-master:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    # deploy:
    #   replicas: 2

  worker2:
    #image: ghcr.io/dask/dask:latest
    image: rhadi2005/dask-dask:latest
    volumes:
      #- ./workspace:/opt/workspace  
      - ./workspace:/home/jovyan/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    command: ["dask", "worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    # deploy:
    #   replicas: 2
    #   restart_policy: unless-stopped

  worker3:
    #image: ghcr.io/dask/dask:latest
    image: rhadi2005/dask-dask:latest
    volumes:
     #- ./workspace:/opt/workspace  
      - ./workspace:/home/jovyan/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    command: ["dask", "worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    # deploy:
    #   replicas: 2

  worker4:
    #image: ghcr.io/dask/dask:latest
    image: rhadi2005/dask-dask:latest
    volumes:
     #- ./workspace:/opt/workspace  
      - ./workspace:/home/jovyan/workspace
      - /home/cloud/dataset:/home/cloud/dataset
    command: ["dask", "worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    # deploy:
    #   replicas: 2

  notebook:
    #image: ghcr.io/dask/dask-notebook:latest
    image: rhadi2005/dask-notebook:latest
    volumes:
      - ./workspace:/home/jovyan/workspace  
      - /home/cloud/dataset:/home/cloud/dataset
    ports:
      - "8888:8888"
    environment:
      - DASK_SCHEDULER_ADDRESS="tcp://scheduler:8786"
